apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy1995
  labels:
    app: autodeploy1995
  namespace: namespace-workflow-1714463553740
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy1995
  template:
    metadata:
      labels:
        app: autodeploy1995
    spec:
      containers:
        - name: autodeploy1995
          image: acrworkflow1714463553740.azurecr.io/image-workflow-1714463553740:latest
          ports:
            - containerPort: 5000